# Generated by Django 2.0.2 on 2018-03-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20180306_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveydetails',
            name='id',
        ),
        migrations.AddField(
            model_name='surveydetails',
            name='survey_num',
            field=models.IntegerField(db_column='survey_num', default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyquestions',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveyquestions',
            name='row_num',
            field=models.IntegerField(db_column='survey_id'),
        ),
    ]
