# Generated by Django 2.0.2 on 2018-03-06 23:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20180304_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveydetails',
            name='row_num',
        ),
        migrations.RemoveField(
            model_name='surveydetails',
            name='survey_id',
        ),
        migrations.RemoveField(
            model_name='surveydetails',
            name='survey_num',
        ),
        migrations.RemoveField(
            model_name='surveyquestions',
            name='data_link',
        ),
        migrations.RemoveField(
            model_name='surveyquestions',
            name='survey_id',
        ),
        migrations.RemoveField(
            model_name='surveyquestions',
            name='survey_name',
        ),
        migrations.RemoveField(
            model_name='surveyquestions',
            name='survey_num',
        ),
        migrations.AddField(
            model_name='surveydetails',
            name='id',
            field=models.AutoField(auto_created=True, default=datetime.datetime(2018, 3, 6, 23, 30, 34, 627509, tzinfo=utc), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveydetails',
            name='survey_key',
            field=models.CharField(db_column='survey_key', default=datetime.datetime(2018, 3, 6, 23, 31, 18, 306065, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyquestions',
            name='survey_key',
            field=models.CharField(db_column='survey_key', default=datetime.datetime(2018, 3, 6, 23, 31, 40, 10173, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveyquestions',
            name='row_num',
            field=models.AutoField(db_column='row_num', primary_key=True, serialize=False),
        ),
    ]
