# Generated by Django 2.0.2 on 2018-03-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20180306_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestions',
            name='id',
        ),
        migrations.AlterField(
            model_name='surveyquestions',
            name='row_num',
            field=models.IntegerField(db_column='row_num', primary_key=True, serialize=False),
        ),
    ]
