# Generated by Django 2.0.2 on 2018-03-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20180306_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveydetails',
            name='survey_num',
            field=models.AutoField(db_column='survey_num', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='surveyquestions',
            name='row_num',
            field=models.AutoField(db_column='row_num', primary_key=True, serialize=False),
        ),
    ]
