# Generated by Django 2.0.1 on 2018-03-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20180304_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveydetails',
            name='survey_questions_document',
            field=models.FileField(db_column='document', upload_to='documents/'),
        ),
    ]
